# 블루투스 기기 이름
CONFIG_ZMK_KEYBOARD_NAME="Joy's KeyPad"

# 블루투스 활성화
CONFIG_ZMK_BLE=y

# 배터리 잔량 보고 비활성화 (0% 표시 제거)
CONFIG_ZMK_BATTERY_REPORTING=n

# 절전 및 대기(딥슬립) 모드 끄기 (항상 연결 유지)
CONFIG_ZMK_SLEEP=n

# 로터리 엔코더 및 GPIO 설정
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_GPIO=y
